/* The compiled css of every static theme, bundled into the standalone build.
 *
 * On the server build each theme is a `style.css` file that the client loads
 * with an `@import` from `/themes/<renderer>/<id>/style.css` (see getThemeBundle
 * in server/homebrew.api.js). Static files can't be imported without a server
 * round trip *and* the themes reference fonts/images by url, so the standalone
 * build precompiles them into this json and hands them to localApi instead.
 *
 * The json is generated by scripts/buildStandalone.js before the bundle is
 * packed, so only the standalone build (client/standalone.jsx) ever requires
 * this file; the server build never touches it.
 */
const loadThemeStyles = ()=>{
	try {
		return require('build/standalone/themeStyles.json');
	} catch (err) {
		console.error('Unable to load the bundled theme styles', err);
		return {};
	}
};

export { loadThemeStyles };
